=== uPortal-Project/uPortal/uportal-war/src/main/resources/xsd/io/user/user-4.0.xsd
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<xs:schema
    xmlns="https://source.jasig.org/schemas/uportal/io/user"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/user"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:up="https://source.jasig.org/schemas/uportal"
    xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal" schemaLocation="../../common-types-4.0.xsd"/>
    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-io-types-4.0.xsd"/>
    
    <xs:element name="user">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="userType">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="template-user">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="userType">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="userType">
        <xs:complexContent>
            <xs:extension base="io:basePortalDataType40">
                <xs:sequence>
                    <xs:element name="default-user" type="xs:string" minOccurs="0"/>
                    <xs:element name="password" type="xs:string" minOccurs="0"/>
                    <xs:element name="lastPasswordChange" type="xs:dateTime" minOccurs="0"/>
                    <xs:element name="attribute" type="attribute" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                
                <xs:attribute name="username" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="attribute">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== uPortal-Project/uPortal/uportal-war/src/main/data/quickstart_entities/user/faculty-lo.user.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<user xmlns="https://source.jasig.org/schemas/uportal/io/user" xmlns:ns2="https://source.jasig.org/schemas/uportal/io/permission-owner" xmlns:ns3="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" xmlns:ns4="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:ns5="https://source.jasig.org/schemas/uportal" xmlns:ns6="https://source.jasig.org/schemas/uportal/io/portlet-type" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" username="faculty-lo" version="4.0" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/user https://source.jasig.org/schemas/uportal/io/user/user-4.0.xsd">
    <default-user>defaultTemplateUser</default-user>
    <attribute>
        <name>givenName</name>
        <value>Faculty</value>
    </attribute>
    <attribute>
        <name>sn</name>
        <value>Layout Owner</value>
    </attribute>
</user>
