=== uPortal-Project/uPortal/uportal-war/src/main/resources/xsd/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<xs:schema xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:up="https://source.jasig.org/schemas/uportal"
    xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal" schemaLocation="../../common-types-4.0.xsd"/>
    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-io-types-4.0.xsd"/>

    <xs:element name="stylesheet-descriptor">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="io:basePortalDataType40">
                    <xs:sequence>
                        <xs:element name="name" type="up:fname-type"/>
                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                        <xs:element name="uri" type="xs:string"/>
                        <xs:element name="url-syntax-helper" type="up:fname-type" minOccurs="0"/>
                        <xs:element name="output-property" type="externalOutputPropertyDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                        <xs:element name="stylesheet-parameter" type="externalStylesheetParameterDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                        <xs:element name="layout-attribute" type="externalLayoutAttributeDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="unique-output-property">
            <xs:selector xpath="output-property"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-stylesheet-parameter">
            <xs:selector xpath="stylesheet-parameter"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-layout-attribute">
            <xs:selector xpath="layout-attribute"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalOutputPropertyDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="externalStylesheetParameterDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="externalLayoutAttributeDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData">
                <xs:sequence>
                    <xs:element name="targetElement" type="xs:NCName" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="externalStylesheetData">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="default-value" type="xs:string" minOccurs="0"/>
            <xs:element name="scope" type="externalStylesheetDataScope"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="externalStylesheetDataScope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PERSISTENT"/>
            <xs:enumeration value="SESSION"/>
            <xs:enumeration value="REQUEST"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== uPortal-Project/uPortal/trunk/uportal-war/src/test/resources/org/jasig/portal/io/xml/ssd/test_4-0.stylesheet-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<stylesheet-descriptor
    xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0"
    xsi:schemaLocation="
        https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd"
>
    <name>DLMXHTML</name>
    <description>Renders DLMTabsColumns as xhtml</description>
    <uri>classpath:/layout/theme/universality/universality.xsl</uri>
    <url-syntax-helper>MultiTabSyntaxHelper</url-syntax-helper>
    <output-property>
        <name>mime-type</name>
        <default-value>text/html</default-value>
        <scope>PERSISTENT</scope>
        <description>The mime type the stylesheet outputs</description>
    </output-property>
    <stylesheet-parameter>
        <name>skin</name>
        <default-value>uportal3</default-value>
        <scope>PERSISTENT</scope>
        <description>Skin name</description>
    </stylesheet-parameter>
    <layout-attribute>
        <name>minimized</name>
        <default-value>false</default-value>
        <scope>PERSISTENT</scope>
        <description>Flag determining if the channel is minimized or not</description>
        <targetElement>channel</targetElement>
        <targetElement>portlet</targetElement>
    </layout-attribute>
</stylesheet-descriptor>

=== uPortal-Project/uPortal/uportal-war/src/main/data/default_entities/stylesheet-descriptor/DLMMobileColumns.stylesheet-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<stylesheet-descriptor xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" xmlns:ns2="https://source.jasig.org/schemas/uportal/io/permission-owner" xmlns:ns3="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:ns4="https://source.jasig.org/schemas/uportal" xmlns:ns5="https://source.jasig.org/schemas/uportal/io/portlet-type" xmlns:ns6="https://source.jasig.org/schemas/uportal/io/user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd">
    <name>DLMMobileColumns</name>
    <description>Presents the DLM layout in terms of tabs and columns.</description>
    <uri>classpath:/layout/structure/mobile-column/mobile-column.xsl</uri>
    <url-syntax-helper>MobileUrlNodeSyntaxHelper</url-syntax-helper>
    <stylesheet-parameter>
        <name>userLayoutRoot</name>
        <scope>REQUEST</scope>
        <description>The id of the focused layout element</description>
    </stylesheet-parameter>
    <stylesheet-parameter>
        <name>detached</name>
        <default-value>false</default-value>
        <scope>REQUEST</scope>
        <description>If the request is for a detached portlet</description>
    </stylesheet-parameter>
    <layout-attribute>
        <name>externalId</name>
        <scope>PERSISTENT</scope>
        <description>Identifier used to reference a tab externally, such as within a URL</description>
        <targetElement>folder</targetElement>
    </layout-attribute>
</stylesheet-descriptor>
