=== uPortal-Project/uPortal/uportal-war/src/main/resources/dtd/PAGSGroupStore.dtd
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<!-- A Group-Store is made up of 0 or more groups. -->
<!ELEMENT Group-Store (group*)>

<!ELEMENT group (group-key,group-name,group-description,selection-test?,members?)>
<!-- A group key must be unique within the document.  A group-name need not be. -->

<!ELEMENT group-key (#PCDATA)>
<!ELEMENT group-name (#PCDATA)>
<!ELEMENT group-description (#PCDATA)>

<!ELEMENT selection-test (test-group+)>
<!-- 
  A selection-test element determines if a person is a member of a group.  It is 
  composed of one or more test-group elements whose results are OR-ed together. 
  If a group does not contain a selection-test, it may have member groups but not
  member entities.  
-->

<!ELEMENT test-group (test*,member-of-group*, not-member-of-group*)>
<!-- 
  A test-group element is made up of 0 or more test elements with an optional
  adhoc-group-test whose results are AND-ed together.
-->

<!ELEMENT test (attribute-name,tester-class,test-value)>
<!-- 
  A test element contains the name of the attribute whose value is to be tested
  (attribute-name), the class that is to perform the test (tester-class), and the 
  value to be compared to the attribute value (test-value).   
-->
<!ELEMENT attribute-name (#PCDATA)>
<!ELEMENT tester-class (#PCDATA)>
<!ELEMENT test-value (#PCDATA)>

<!ELEMENT member-of-group (#PCDATA)>
<!ELEMENT not-member-of-group (#PCDATA)>

<!ELEMENT members (member-key*)>
<!-- The optional members element contains keys of member groups. -->
<!ELEMENT member-key (#PCDATA)>

=== uPortal-Project/uPortal/uportal-impl/src/main/resources/properties/groups/PAGSGroupStoreConfig.xml
<?xml version="1.0"?>
<!DOCTYPE Group-Store PUBLIC "-//uPortal//PAGSGroupStore/EN" "PAGSGroupStore.dtd">

<!--
    PAGSGroupStoreConfig.xml is used to configure the person attributes group store.
    See PAGSGroupStore.dtd for xml grammar.

    To control the attributes that are available, see ../personDirectory.xml.

    Author: Dan Ellentuck, de3@columbia.edu
    Version $Revision$

    This sample configuration sets up 4 groups in the following relationship:

    All (0)
     |- Users (1)
     |- Short First Names (2)
         |- Ds and Staff (3)

    that is, Users (1) and Short First Names (2) are members of All (0), and Ds and Staff
    is a member of Short First Names (2).  These declarations can be used to assess group
    membership for the 6 users delivered in the base code (demo, student, etc.)

-->


<Group-Store>

<!-- Group declarations: -->

<!--
  Group 0: "PAGS Root"
-->
  <group>
    <group-key>0</group-key>
    <group-name>PAGS Root</group-name>
    <group-description>Root group for all PAGS groups.  Convenience for adding PAGS groups to a local group.</group-description>
    <members>
      <member-key>1</member-key>
    </members>
  </group>


<!--
  Group 1: "All Users (PAGS)"
  All IPersons are memebers of this group
-->
  <group>
    <group-key>1</group-key>
    <group-name>All Users (PAGS)</group-name>
    <group-description>All Portal Users</group-description>
    <selection-test>
      <test-group>
        <test>
          <tester-class>org.jasig.portal.groups.pags.testers.AlwaysTrueTester</tester-class>
        </test>
      </test-group>
    </selection-test>
  </group>
  
  
  <!--==================== Other Examples ====================-->


<!--
  Group 2: "Short First Names"
  givenName has 5 or fewer characters
-->
<!-- 
  <group>
    <group-key>2</group-key>
    <group-name>Short First Names</group-name>
    <group-description>Portal users whose first names are between 1 and 5 characters long</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^.{1,5}$</test-value>
        </test>
      </test-group>
    </selection-test>
    <members>
      <member-key>3</member-key>
    </members>
  </group>
 -->

<!--
  Group 3: "Ds and Students"
  givenName starts with D or equals "Student" since the results of the test-group elements are
  OR-ed together.  HOWEVER, since this group is a member of group 2, members of this group must
  also qualify as members of group 2, i.e., given name must have 5 or fewer characters.  As a
  result, Student User should not show up as a member.
-->
<!-- 
  <group>
    <group-key>3</group-key>
    <group-name>Ds and Students</group-name>
    <group-description>Portal users whose first names begin with D or equal Student</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^D.*$</test-value>
        </test>
      </test-group>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.StringEqualsTester</tester-class>
          <test-value>Student</test-value>
        </test>
      </test-group>
    </selection-test>
  </group>
 -->


<!-- End Group declarations: -->

</Group-Store>

=== uPortal-Project/uPortal/trunk/uportal-war/src/main/resources/properties/groups/PAGSGroupStoreConfig.xml
<?xml version="1.0"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<!DOCTYPE Group-Store PUBLIC "-//uPortal//PAGSGroupStore/EN" "PAGSGroupStore.dtd">

<!--
    PAGSGroupStoreConfig.xml is used to configure the person attributes group store.
    See PAGSGroupStore.dtd for xml grammar.

    To control the attributes that are available, see ../personDirectory.xml.

    Author: Dan Ellentuck, de3@columbia.edu
    Version $Revision$

    This sample configuration sets up 4 groups in the following relationship:

    All (0)
     |- Users (1)
     |- Short First Names (2)
         |- Ds and Staff (3)

    that is, Users (1) and Short First Names (2) are members of All (0), and Ds and Staff
    is a member of Short First Names (2).  These declarations can be used to assess group
    membership for the 6 users delivered in the base code (demo, student, etc.)

-->


<Group-Store>

<!-- Group declarations: -->

<!--
  Group pags_root: "PAGS Root"
  IMPORTANT: The PAGS Root group is REQUIRED for uPortal to function. It Must be a member of the Everyone group in the
  local group store
-->
  <group>
    <group-key>pags_root</group-key>
    <group-name>PAGS Root</group-name>
    <group-description>Root group for all PAGS groups.  Convenience for adding PAGS groups to a local group.</group-description>
    <members>
      <member-key>all_users</member-key>
    </members>
  </group>


<!--
  Group all_users: "All Users (PAGS)"
  All IPersons are memebers of this group
  IMPORTANT: The All Users group is REQUIRED for uPortal to function. It Must be a member of the PAGS Root group
-->
  <group>
    <group-key>all_users</group-key>
    <group-name>All Users (PAGS)</group-name>
    <group-description>All Portal Users</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name></attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.AlwaysTrueTester</tester-class>
          <test-value></test-value>
        </test>
      </test-group>
    </selection-test>
  </group>
  
  <group>
    <group-key>authenticated_users</group-key>
    <group-name>Authenticated Users</group-name>
    <group-description>All Authenticated Portal Users</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name></attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.GuestUserTester</tester-class>
          <test-value>false</test-value>
        </test>
      </test-group>
    </selection-test>
  </group>
  
  <!--==================== Other Examples ====================-->


<!--
  Group 2: "Short First Names"
  givenName has 5 or fewer characters
-->
<!-- 
  <group>
    <group-key>2</group-key>
    <group-name>Short First Names</group-name>
    <group-description>Portal users whose first names are between 1 and 5 characters long</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^.{1,5}$</test-value>
        </test>
      </test-group>
    </selection-test>
    <members>
      <member-key>3</member-key>
    </members>
  </group>
 -->

<!--
  Group 3: "Ds and Students"
  givenName starts with D or equals "Student" since the results of the test-group elements are
  OR-ed together.  HOWEVER, since this group is a member of group 2, members of this group must
  also qualify as members of group 2, i.e., given name must have 5 or fewer characters.  As a
  result, Student User should not show up as a member.
-->
<!-- 
  <group>
    <group-key>3</group-key>
    <group-name>Ds and Students</group-name>
    <group-description>Portal users whose first names begin with D or equal Student</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^D.*$</test-value>
        </test>
      </test-group>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.StringEqualsTester</tester-class>
          <test-value>Student</test-value>
        </test>
      </test-group>
    </selection-test>
  </group>
 -->


<!-- End Group declarations: -->

</Group-Store>
