=== uPortal-Project/uPortal/uportal-war/src/main/resources/dtd/tables.dtd
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<!-- tables.dtd -->
<!-- Use to validate tables.xml that is used with DbLoader -->

<!ELEMENT tables (table+) >
<!ATTLIST table
   sinceMajor  CDATA #REQUIRED
   sinceMinor  CDATA #REQUIRED>
<!ELEMENT table (name, desc, columns, primary-key*,not-null*,unique*,index*) >
<!ELEMENT columns (column+)>
<!ELEMENT column (name, type, param?, desc?, key?)>
<!ATTLIST column
   sinceMajor  CDATA #IMPLIED
   sinceMinor  CDATA #IMPLIED>
<!ELEMENT param (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT primary-key (#PCDATA)>
<!ELEMENT unique (name, column-ref*)>
<!ELEMENT not-null (#PCDATA)>
<!ELEMENT index (name, column-ref*)>
<!ELEMENT column-ref (#PCDATA)>

=== uPortal-Project/uPortal/uportal-war/src/main/resources/properties/db/tables-l10n.xml
<?xml version="1.0"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<!-- $Revision$ -->
<!DOCTYPE tables PUBLIC "-//uPortal//Tables/EN" "tables.dtd">

<tables>

  <table>
    <name>UP_PERSON_DIR</name>
    <desc>Directory information for a given person, including the MD5 password. Emulates a simple external authentication service, like LDAP.</desc>
    <columns>
      <column> <name>USER_NAME</name>       <type>VARCHAR</type>   <param>35</param>
        <desc>Authentication prinicipal - Primary key and foreign key foreign key to external authentication system (which is what up_person_dir emulates)</desc>
      </column>
      <column> <name>ENCRPTD_PSWD</name>    <type>VARCHAR</type>   <param>64</param>
        <desc>MD5 authentication credential - or user's password</desc>
      </column>
      <column> <name>LST_PSWD_CGH_DT</name> <type>TIMESTAMP</type>
        <desc>Date of last password change</desc>
      </column>
      <column> <name>FIRST_NAME</name>	    <type>VARCHAR</type>   <param>15</param>
        <desc>Person's first name</desc>
      </column>
      <column> <name>LAST_NAME</name>       <type>VARCHAR</type>   <param>15</param>
        <desc>Person's last name</desc>
      </column>
      <column> <name>EMAIL</name>           <type>VARCHAR</type>   <param>60</param>
        <desc>Person's e-mail address</desc>
      </column>
    </columns>
    <not-null>USER_NAME</not-null>
    <primary-key>USER_NAME</primary-key>
    <index>
        <name>UPPD_NAME_PSWD_IDX</name>
        <column-ref>USER_NAME</column-ref>
        <column-ref>ENCRPTD_PSWD</column-ref>
    </index>
  </table>

  <table>
    <name>UP_GROUP</name>
    <desc>Entries that uniquely identify a uPortal group</desc>
    <columns>
      <column> <name>GROUP_ID</name>        <type>VARCHAR</type>     <param>240</param>
        <desc>Group ID is a unique sequence number used by the portal - primary key, see UP_SEQUENCE</desc>
      </column>
      <column> <name>CREATOR_ID</name>      <type>VARCHAR</type>     <param>240</param>
        <desc>Who created this group, foreign key USER_ID of table UP_USER</desc>
      </column>
      <column> <name>ENTITY_TYPE_ID</name>  <type>INTEGER</type>
        <desc>The entity to be called when a member of this group, foreign key ENTITY_TYPE_ID of table UP_ENTITY_TYPE</desc>
      </column>
      <column> <name>GROUP_NAME</name>      <type>VARCHAR</type>     <param>255</param>
        <desc>Short textual name of the group for finding group</desc>
      </column>
      <column> <name>DESCRIPTION</name>     <type>VARCHAR</type>     <param>255</param>
        <desc>Longer textual description of group to view a brief description of group</desc>
      </column>
    </columns>
    <primary-key>GROUP_ID</primary-key>
    <not-null>CREATOR_ID</not-null>
    <not-null>ENTITY_TYPE_ID</not-null>
    <not-null>GROUP_NAME</not-null>
    <not-null>GROUP_ID</not-null>
    <index>
        <name>UPG_GROUP_NAME_IDX</name>
        <column-ref>GROUP_NAME</column-ref>
    </index>
  </table>

</tables>
